### ISSUE TITLE
Add the `libc6-i386` package as part of the `x86-64` / `amd64` image

### ISSUE THREAD

**Issue by cipriancraciun** [finnix/finnix#35]
I know that Finnix supports only the `amd64` architecture.

However by just installing (as part of the SquashFS image) the standard Debian package `libc6-i386` (which has no other dependencies that are not already in Finnix), it would enable running 32bit applications without a problem.

One such an application example is the pre-built SysLinux package available at `https://mirrors.edge.kernel.org/pub/linux/utils/boot/syslinux/Testing/6.04/syslinux-6.04-pre1.tar.xz`, which is often used to create or fix bootable mediums.

Other uses might be legacy binaries used in rescuing a system.

**Comment by rfinnie** [comment]
Sorry for the delay on this, it will be added for Finnix 126! I was originally sitting on considering this because apt was reporting 20MB additional disk (of which I was estimating 50% compressed root savings) which would have been high for a relatively niche (but valid) use case. But it turns out net addition was only about 2MB.

**Comment by rfinnie** [comment]
https://blog.finnix.org/2024/07/04/finnix-126-released/

**Comment by cipriancraciun** [comment]
Thanks!  I'll test when I get some free time.
